### ISSUE TITLE
Openvidu always recording test page instead of recording layout.

### ISSUE THREAD

**Issue by Samataro** [OpenVidu/openvidu#296]
Hi.

I have a problem with openvidu: it recording test page from <openvidu.publicurl> instead of conference stream.

![record page](https://user-images.githubusercontent.com/3612797/61815530-189d6e80-ae53-11e9-9928-d232c9674652.png)

I found this line in log files:
```
openvidu_1             | [INFO] 2019-07-22 18:52:24,051 [Thread-4] io.openvidu.server.recording.service.ComposedRecordingService (startRecordingWithVideo) - Recorder connecting to url https://OPENVIDUAPP:mysupersecret@calls.myhost.com:4443/#/layout-best-fit/kmg6b6a4k90toc2n/mysupersecret/4443/false
```

But when I open this url, it redirecting me to test page `calls.myhost.com:4443/#/` so this page is always recorded in all sessions.

Here is my docker-compose file:

```
networks:
  frontend:
    driver: ${NETWORKS_DRIVER}  # bridge
  backend:
    driver: ${NETWORKS_DRIVER}  # bridge

<...>

openvidu:
      image: openvidu/openvidu-server-kms:2.9.0
      environment:
        - openvidu.secret=${OPENVIDU_SECRET}
        - openvidu.publicurl=${OPENVIDU_PUBLIC_URL}      # https://calls.myhost.com:4443
        - openvidu.recording=true
        - openvidu.recording.path=/mnt/data/call_recods
        - openvidu.recording.public-access=true
        - server.port=${OPENVIDU_PORT}                   # 4443
        - server.ssl.enabled=true
      volumes:
        - /mnt/data/call_recods:/mnt/data/call_recods
        - /var/run/docker.sock:/var/run/docker.sock
      ports:
        - "${OPENVIDU_PORT}:${OPENVIDU_PORT}"
      networks:
        - backend
```

Logs from openvidu-server-kms and openvidu-recording containers:
[openvidu-logs.log](https://github.com/OpenVidu/openvidu/files/3428112/openvidu-logs.log)
[recorder-logs.log](https://github.com/OpenVidu/openvidu/files/3428113/recorder-logs.log)
