### ISSUE TITLE
Issue reaching the rest api

### ISSUE THREAD

**Issue by happyDemon** [OpenVidu/openvidu#47]
locally I have openvidu/openvidu-server-kms running, dockerized along with a few other services, like a backend to help me manage a few things. I'm having trouble connecting to openvidu's and kurento's api.

part of docker-compose.yml:
```

  #openvidu
  openvidu-server-kms:
   image: openvidu/openvidu-server-kms:1.7.0
   ports:
     - 8443:8443
   environment:
     - KMS_STUN_IP=stun.l.google.com
     - KMS_STUN_PORT=19302
     - openvidu.secret=MY_SECRET
     - openvidu.publicurl=docker
   expose:
      - "8443"
      - "8888"
      - "80"
```

When I follow the docs (https://openvidu.io/docs/reference-docs/REST-API/)
I set the endpoint(http://openvidu-server-kms/api/sessions), along with the headers and a body, it says 'Connection refused',
I also tried switching to 9091 to access kurento, but that seemed to be a websocket connection.

Is there something I'm missing?
